<a href="https://colab.research.google.com/github/chandanakrishnan/Programming-logic/blob/main/5_Conditional_Statement.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Programming Introduction + Python + Hands On**
> **Professor: Sthefanie Passo**

# **Conditional Statement**

Any computer program can be written
combining the three basic types of
programming:

* Sequential Statement
* Conditional Statement
* Repetition Statement

## **Sequential Statement**
It is the simplest programming structure.
The algorithm's command flows follow the same linear sequence as our common script:


* Top to bottom
*   From left to right
Its basic structure is the repetition of **sequential command**:

```
Action1;
```

```
Action1;
Action2;
Action3;
Action4;
Action5;
```
Example:

In [ ]:
# Take the average from the grades
g1, g2, g3 = 8.9, 8.0, 8.9
average = (g1+g2+g3)/3
print("The average is: ", average)

The average is:  8.6


## **Conditional Structure**
The **IF ... ELSE** structure is the simplest control structure in programming language. This structure allows to execute one of **several blocks of instructions**.

The control of which block will be executed is given by a condition, **numeric or logical expression**. This structure can be presented in two different ways: simple or compound conditional.

In the end the condition will have a value of **True** or **False**

![alt text](https://assets-global.website-files.com/6184b461a39ff1011f8c0582/620239fdd8763fe2a551f490_If-else%20Flowchart.png)

Example of simple conditional structure:

In [ ]:
grade = float(input("Digit your grade (0-10): "))
if(grade > 5):
  print("Congratulations!")

Digit your grade (0-10): 3


Compound conditional: Decision of two blocks. It is also possible to write a structure that executes one between two blocks of instructions.

![alt text](https://d1whtlypfis84e.cloudfront.net/guides/wp-content/uploads/2021/06/29090322/if-else-flowchart.jpg)

Example:

In [ ]:
grade = float(input("Digit your grade (0-10): "))
if(grade > 5):
  print("Congratulations!")
else:
  print("Try again!")


Digit your grade (0-10): 4
Try again!


Ternary operator



```
answer = a if a < b else b

print(answer)
```



In [ ]:
grade = float(input("Digit your grade (0-10): "))
answer = "Congratulations" if grade>5 else "Try again"
print(answer)

Digit your grade (0-10): 2
Try again


In order for the **code blocks** to work according to the condition, we have to leave our code **idented** because otherwise it can generate errors.

To identify, press the *tab*

![alt text](https://d1whtlypfis84e.cloudfront.net/guides/wp-content/uploads/2021/06/29090812/Nested-if-flowchart.jpg)

Follow the table and write the conditional statement according to the grade



```
Grade is greater or equal to 8-10   ->   Congratulations
Grade is greater or equal to 7-8   ->    Good Job
Grade is greater or equal to 5-7   ->    Better luck next time
Lower then 5  ->    Fail
```



In [ ]:
grade = float(input("Digit your grade (0-10): "))

if(grade >= 8 and grade <10): #8<grade<10 python don't recognize
  print("Congratulations")
elif (grade>= 7 and grade<8):
  print("Good job")
elif (grade>= 5 and grade<7):
    print("Better luck next time")
elif (grade< 5):
    print("Fail")

Digit your grade (0-10): 2
Fail


We will now see an example using **logical and arithmetic operators**, transforming the following sentence into an algorithm.

First using the logical AND operator:

**"I go to the movie teather IF I have time AND money".**

In [ ]:
time = str(input("Do you have time (y/N)? "))
money = str(input("Do you have money (y/N)? "))

if(time=='y' and money=='y'):
  print("I'm going to the movies!")
else:
  print("Another day...")


Do you have time (y/N)? y
Do you have money (y/N)? y
I'm going to the movies!


True Table AND (MULTIPLICATION 0 and 1)
> T AND T = T //1 X 1 = 1

> T AND F = F //1 X 0 = 0

> F AND T = F //0 X 1 = 0

> F AND F = F //0 X 0 = 0

And with the logical operator OR?

Follow the thread:

**"I will go to the club IF my friends are there OR if my crush is there".**

In [ ]:
frinds = str(input("my friend coming to club (y/n)?"))
crush = str(input("my crush coming to club (y/n)?"))

if(frinds=='y' or crush=='y'):
  print("I am going to the club")
else:
    print("Another day...")

my friend coming to club (y/n)?n
my crush coming to club (y/n)?n
Another day...


True Table OR (SUM 0 and 1)
> T OR T = T //1 + 1 = 1

> T OR F = T //1 + 0 = 1

> F OR T = T //0 + 1 = 1

> F OR F = F //0 + 0 = 0

Ready!

Now that we have learned the main conditional structures and how to use them, **hands-on** !!!

![alt text](https://media1.tenor.com/images/84e36470c3e534a5e71c208cd872d177/tenor.gif?itemid=6108221)

# **Homework**

**1)** Write an algorithm in Python that receives a name as input and checks if it is the same as its name. Print as appropriate:

*   "Correct name"
* "Incorrect Name"


In [ ]:
name = str(input("Please enter your name:"))

if(name=='stefanie'):
  print("correct name")
else:
  print("incorrect name")



Please enter your name:stefanie
correct name


**2)** Write an algorithm in python that reads three real numbers from the keyboard and verify that the first is greater than the sum of the other two.

In [ ]:
A = float(input("Digit a number for A: "))
B = float(input("Digit a number for B: "))
C = float(input("Digit a number for C: "))
if(A>B+C):
  print("First number is greater than sum of other two")
else:
  print("First number is not greater then sum of other two")

Digit a number for A: 10
Digit a number for B: 7
Digit a number for C: 1
First number is greater than sum of other two


**3)** A technology store decided to make a mega promotion of console games. The game prices are identified by the colored labels, one in each game. Develop the algorithm that from the entry of the color of the label, the software shows the price. The store currently has the following price list:

Green: $ 10.00

Blue: $ 20.00

Yellow: $ 30.00

Red: $ 40.00

In [ ]:
game = str(input("Enter the game you want to play:"))

if(game=='volleyball'):
  print("green:$ 10.00")
elif(game=='baseketball'):
  print("blue:$ 20.00")
if(game=='tennis'):
  print("yellow:$ 30.00")
elif(game=='hockey'):
  print("red:$ 40.00")



Enter the game you want to play:hockey
red:$ 40.00


**4)** Request 3 numbers from the user and print them in a ascending order using if and else statement.


In [ ]:
#example with just 2 numbers
n1 = int(input("Digit a number: ")) #5
n2 = int(input("Digit a number: ")) #2
n3 = int(input ("Digit a number: "))

if(n1<=n2) and (n1<=n3):
  if(n2<=n3):
    print(n1,n2,n3)
  else:
     print(n1,n3,n2)
elif(n2<=n1) and (n2<=n3):
  if(n1<=n3):
    print(n2,n1,n3)
  else:
    print(n2,n3,n1)
if(n3<=n1) and (n3<=n2):
  if(n1<=n2):
    print(n3,n1,n2)
  else:
      print(n3,n2,n1)


#output 2, 5

Digit a number: 7
Digit a number: 1
Digit a number: 9
1 7 9


In [ ]:
n1 = int(input("Digit a number: ")) #1
n2 = int(input("Digit a number: ")) #3
n3 = int(input("Digit a number: ")) #2

if(n1 <= n2 and n1<=n3):
  if(n2<=n3):
    print(n1,", ", n2, ", ", n3)
  else:
    print(n1,", ", n3, ", ", n2)
elif ...




Digit a number: 1
Digit a number: 2
Digit a number: 3
1 ,  2 ,  3


**6)** Help Starbucks giving 3 different options of coffee (iced caramel brulee latte, matcha latte, cappucino), temperature (hot or cold) and size (S,M,L). Calculate the final price of the order.


In [ ]:
coffee = str(input("Choose the coffee you want :iced caramel brulee latte, matcha latte, cappucino? "))
temperature = str(input("Do you want it hot or cold? "))
size = str(input("please select the size : S,M,L? "))

#iced caramel brulee latte
if(coffee=='iced caramel brulee latte' and temperature=='hot'and size=='S'):
  print("Final price = $5.5")
elif (coffee=='iced caramel brulee latte'and temperature=='hot' and size=='M'):
  print("Final price = $6.5")
elif(coffee=='iced caramel brulee latte'and temperature=='hot' and size=='L'):
  print("Final price = $7.5")
elif(coffee=='iced caramel brulee latte' and temperature=='cold'and size=='S'):
  print("Final price = $5")
elif (coffee=='iced caramel brulee latte'and temperature=='cold' and size=='M'):
  print("Final price = $6")
elif(coffee=='iced caramel brulee latte'and temperature=='cold' and size=='L'):
  print("Final price = $7")

#matcha latte
if(coffee=='matcha latte' and temperature=='hot'and size=='S'):
  print("Final price = $5.5")
elif (coffee=='matcha latte'and temperature=='hot' and size=='M'):
  print("Final price = $6.5")
elif(coffee=='matcha latte'and temperature=='hot' and size=='L'):
  print("Final price = $7.5")
elif(coffee=='matcha latte' and temperature=='cold'and size=='S'):
  print("Final price = $5")
elif (coffee=='matcha latte'and temperature=='cold' and size=='M'):
  print("Final price = $6")
elif(coffee=='matcha latte'and temperature=='cold' and size=='L'):
  print("Final price = $7")

#cappucino
if(coffee=='cappucino' and temperature=='hot'and size=='S'):
  print("Final price = $5.5")
elif (coffee=='cappucino'and temperature=='hot' and size=='M'):
  print("Final price = $6.5")
elif(coffee=='cappucino'and temperature=='hot' and size=='L'):
  print("Final price = $7.5")
elif(coffee=='cappucino' and temperature=='cold'and size=='S'):
  print("Final price = $5")
elif (coffee=='cappucino'and temperature=='cold' and size=='M'):
  print("Final price = $6")
elif(coffee=='cappucino'and temperature=='cold' and size=='L'):
  print("Final price = $7")




Choose the coffee you want :iced caramel brulee latte, matcha latte, cappucino? cappucino
Do you want it hot or cold? hot
please select the size : S,M,L? S
Final price = $5.5


Observation about if, elif and else:

In [ ]:
a = 1
b = 2
if(a>b): #in the if we need to define a conditional
  print(a,", ",b)
else(a<b): # in the else we don't have a conditional
  print(a,", ",b)




SyntaxError: expected ':' (<ipython-input-14-a896cc03274e>, line 5)

We can write the code above in 2 different ways:

In [ ]:
a = 1
b = 2
if(a>b): #in the if we need to define a conditional
  print(a,", ",b)
else: # in the else we don't have a conditional
  print(a,", ",b)


1 ,  2


In [ ]:
a = 1
b = 2
if(a>b): #in the if we need to define a conditional
  print(a,", ",b)
elif(a<b): # in the elif we have a conditional
  print(a,", ",b)

1 ,  2


In [ ]:
import numpy as np
from scipy.interpolate import splrep, splev

# Sample data
np.random.seed(0)  # For reproducibility
data = np.random.rand(20, 10)

# New x-axis values for interpolation (5 points)
x_old = np.linspace(0, 1, 10)
x_new = np.linspace(0, 1, 5)

# Container for the new data
new_data = np.zeros((20, 5))

# Interpolate each row
for i in range(20):
    # Compute B-spline representation of the data
    tck = splrep(x_old, data[i, :], s=0)
    # Evaluate the B-spline at new x-axis values
    new_data[i, :] = splev(x_new, tck)

# Display the new data shape
print(new_data.shape)
print(new_data)

(20, 5)
[[0.5488135  0.58987386 0.55524287 0.76249385 0.38344152]
 [0.79172504 0.70279557 0.0129413  0.64963277 0.87001215]
 [0.97861834 0.55404093 0.37579483 0.76170578 0.41466194]
 [0.26455561 0.48805895 0.25612009 0.57403945 0.6818203 ]
 [0.3595079  0.54451596 0.79087019 0.10971719 0.36371077]
 [0.57019677 0.82911697 0.16130452 0.35149684 0.24442559]
 [0.15896958 0.58337442 0.23588364 0.21148406 0.09609841]
 [0.97645947 0.92306199 0.38613219 0.16469297 0.11872772]
 [0.31798318 0.17479386 0.34465579 0.17127128 0.9292962 ]
 [0.31856895 0.23307039 0.11327064 0.09086873 0.00469548]
 [0.67781654 0.8736218  0.33876858 0.60733278 0.95274901]
 [0.44712538 0.55587586 0.60776372 0.6563788  0.69253159]
 [0.72525428 0.94442117 0.5681229  0.16885484 0.29007761]
 [0.61801543 0.13502078 0.60529862 0.63273118 0.43141844]
 [0.8965466  0.55589664 0.81901013 0.7247145  0.99884701]
 [0.1494483  0.23431161 0.41811394 0.61591842 0.069167  ]
 [0.69742877 0.77513014 1.01580431 0.20044033 0.17162968]
 [0.52